name: Update Untis Calendar (hourly)

on:
  schedule:
    - cron: "0 * * * *"  # stündlich
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env from secrets
        run: |
          echo "WEBUNTIS_SERVER=${{ secrets.WEBUNTIS_SERVER }}" >> .env
          echo "WEBUNTIS_SCHOOL=${{ secrets.WEBUNTIS_SCHOOL }}" >> .env
          echo "WEBUNTIS_USERNAME=${{ secrets.WEBUNTIS_USERNAME }}" >> .env
          echo "WEBUNTIS_PASSWORD=${{ secrets.WEBUNTIS_PASSWORD }}" >> .env
          echo "WEBUNTIS_CLIENT=${{ secrets.WEBUNTIS_CLIENT }}" >> .env
          echo "UNTIS_STUDENT_ID=${{ secrets.UNTIS_STUDENT_ID }}" >> .env
          echo "UNTIS_CLASS_ID=${{ secrets.UNTIS_CLASS_ID }}" >> .env
          echo "TIMEZONE=Europe/Berlin" >> .env
          echo "ICS_OUTPUT_PATH=./docs/untis.ics" >> .env

      - name: Build ICS
        run: python untis_to_ics.py

      - name: Commit and push ICS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/untis.ics
          git commit -m "Update ICS $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
