name: Test Untis REST

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests python-dotenv

      - name: Create .env from secrets
        run: |
          echo "WEBUNTIS_SERVER=${{ secrets.WEBUNTIS_SERVER }}" >> .env
          echo "WEBUNTIS_SCHOOL=${{ secrets.WEBUNTIS_SCHOOL }}" >> .env
          echo "WEBUNTIS_USERNAME=${{ secrets.WEBUNTIS_USERNAME }}" >> .env
          echo "WEBUNTIS_PASSWORD=${{ secrets.WEBUNTIS_PASSWORD }}" >> .env
          echo "WEBUNTIS_CLIENT=${{ secrets.WEBUNTIS_CLIENT }}"   >> .env
          echo "UNTIS_STUDENT_ID=${{ secrets.UNTIS_STUDENT_ID }}" >> .env
          echo "UNTIS_CLASS_ID=${{ secrets.UNTIS_CLASS_ID }}"     >> .env
          echo "TIMEZONE=Europe/Berlin"                           >> .env

      - name: Run REST test script
        run: python test_rest_endpoints.py
